fix(ybn): attempt to fix random AttributeErrors in CollisionMatFlags
Occasionally the following error would occur during import since 1415dbb7431d0febdb23adfd14c76f23aed79ec2:
```
AttributeError: 'CollisionMatFlags' object has no attribute 'set_lo_flags'
```

Restarting Blender normally fixes it. Still unknown why it occurs, seems
related to updating Sollumz or changing branches.

Moved those functions outside the class to see if the issue gets fixed.